### ISSUE TITLE
The "accept cookie" -buttons seem to be broken

### ISSUE THREAD

**Issue by sofiahag** [MultiQC/website#51]
They seem unresponsive. I tried clicking them in chrome, safari, and firefox.

![Skärmavbild 2023-04-12 kl  16 59 06](https://user-images.githubusercontent.com/37932118/231498889-2e1d9f8b-e314-4a25-9a94-21077f21bef8.png)

**Comment by ewels** [comment]
Took me a little while to figure out why the buttons weren't working, but I think I got it 👍🏻

**Comment by sofiahag** [comment]
Works now! 🎉
