### ISSUE TITLE
The "installation instructions" link at the bottom of the home page gives error 404

### ISSUE THREAD

**Issue by clstacy** [MultiQC/website#60]
Very grateful for this resource. I found what I think is a dead URL on the homepage of multiqc.info, when I scroll to the bottom of the page and see a hyperlinked "installation instructions" above the view on github button, clicking the blue hyperlink gives an error 404 when trying to link to the below url: https://multiqc.info/docs/usage/installation

**Comment by ewels** [comment]
Good spot, thanks! Link updated in https://github.com/MultiQC/website/commit/811e64cd3ae7950094b1b5a797d86519ced169fc
